/**
 * GENERATED by tokens/build-brand-snippet.mjs from tokens/brands/portfolio.json.
 * Do not edit. Change the pack and rebuild.
 *
 * Writes the wise / healf / ticketmaster / asos / deesyn palette into the open Figma file: adds this
 * pack's primitives to "01 Primitives" and repoints "02 Semantic" in both
 * modes to alias them. Paste into the Figma Desktop Bridge plugin console with
 * the brand's file open, then run tokens/brand-export.snippet.js and check the
 * checksum against `node tokens/verify-brands.mjs`.
 *
 * It ADDS and REPOINTS; it deletes nothing. Existing primitives are left in
 * place, which is what keeps the file a superset of where it started and makes
 * running this twice harmless.
 */
const PRIM = "Portfolio/Teal/50 #e7f8f5,Portfolio/Teal/100 #c2ede7,Portfolio/Teal/200 #8eded4,Portfolio/Teal/300 #59cdc1,Portfolio/Teal/400 #41b7ac,Portfolio/Teal/500 #329b91,Portfolio/Teal/600 #267f76,Portfolio/Teal/700 #16625b,Portfolio/Teal/800 #0a4641,Portfolio/Teal/900 #01302c,Portfolio/Navy/50 #eef0f5,Portfolio/Navy/100 #d3dae5,Portfolio/Navy/200 #a9b4c8,Portfolio/Navy/300 #808fa9,Portfolio/Navy/400 #576a8d,Portfolio/Navy/500 #2f4671,Portfolio/Navy/600 #203357,Portfolio/Navy/700 #1d2e4e,Portfolio/Navy/800 #162542,Portfolio/Navy/900 #0e1728,Portfolio/Neutral/0 #ffffff,Portfolio/Neutral/50 #f5f6f8,Portfolio/Neutral/100 #ecedee,Portfolio/Neutral/200 #d9dbde,Portfolio/Neutral/300 #c6c8cc,Portfolio/Neutral/400 #b0b2b8,Portfolio/Neutral/500 #6b7080,Portfolio/Neutral/600 #4a4d56,Portfolio/Neutral/700 #2e3038,Portfolio/Neutral/800 #1a1a1c,Portfolio/Neutral/900 #0a0a0b";
const LIGHT = "bg/canvas Portfolio/Neutral/0,bg/subtle Portfolio/Neutral/50,bg/surface Portfolio/Neutral/0,bg/surface-raised Portfolio/Neutral/50,bg/overlay Portfolio/Neutral/0,bg/inverse Portfolio/Navy/900,bg/widget Alpha/Black 4,bg/widget-hover Alpha/Black 15,bg/scrim Alpha/Black 40,band/base Portfolio/Neutral/0,band/sunken Portfolio/Neutral/50,fg/primary Portfolio/Navy/900,fg/secondary Portfolio/Neutral/500,fg/tertiary Portfolio/Neutral/300,fg/inverse Portfolio/Neutral/0,fg/accent Portfolio/Teal/700,fg/on-accent Portfolio/Neutral/0,fg/link Portfolio/Teal/700,fg/link-hover Portfolio/Teal/800,border/subtle Alpha/Black 4,border/default Portfolio/Neutral/200,border/strong Portfolio/Neutral/400,border/focus Portfolio/Teal/600,action/primary-bg Portfolio/Navy/900,action/primary-fg Portfolio/Neutral/0,action/accent-bg Portfolio/Teal/600,action/accent-fg Portfolio/Neutral/0,action/secondary-bg Alpha/Black 4,action/secondary-fg Portfolio/Navy/900,action/disabled-bg Portfolio/Neutral/50,action/disabled-fg Portfolio/Neutral/400,action/primary-bg-hover Portfolio/Navy/700,action/secondary-bg-hover Alpha/Black 15,action/ghost-bg-hover Alpha/Black 4,status/info Portfolio/Teal/700";
const DARK = "bg/canvas Portfolio/Navy/900,bg/subtle Portfolio/Navy/800,bg/surface Portfolio/Navy/800,bg/surface-raised Portfolio/Navy/700,bg/overlay Portfolio/Navy/700,bg/inverse Portfolio/Neutral/0,bg/widget Alpha/White 6,bg/widget-hover Alpha/White 10,bg/scrim Alpha/Black 70,band/base Portfolio/Navy/900,band/sunken Portfolio/Navy/800,fg/primary Portfolio/Neutral/0,fg/secondary Alpha/White 70,fg/tertiary Alpha/White 50,fg/inverse Portfolio/Navy/900,fg/accent Portfolio/Teal/400,fg/on-accent Portfolio/Neutral/0,fg/link Portfolio/Teal/400,fg/link-hover Portfolio/Teal/300,border/subtle Alpha/White 10,border/default Portfolio/Navy/700,border/strong Portfolio/Navy/500,border/focus Portfolio/Teal/400,action/primary-bg Portfolio/Neutral/0,action/primary-fg Portfolio/Navy/900,action/accent-bg Portfolio/Teal/600,action/accent-fg Portfolio/Neutral/0,action/secondary-bg Alpha/White 14,action/secondary-fg Portfolio/Neutral/0,action/disabled-bg Portfolio/Navy/800,action/disabled-fg Portfolio/Navy/400,action/primary-bg-hover Portfolio/Neutral/100,action/secondary-bg-hover Alpha/White 24,action/ghost-bg-hover Alpha/White 6,status/info Portfolio/Teal/400";

const pairs = (s) => s.split(',').map((r) => { const i = r.indexOf(' '); return [r.slice(0, i), r.slice(i + 1)]; });
const hexToRgb = (h) => {
  const n = h.replace('#', '');
  const v = (i) => parseInt(n.slice(i, i + 2), 16) / 255;
  return n.length >= 8 ? { r: v(0), g: v(2), b: v(4), a: v(6) } : { r: v(0), g: v(2), b: v(4), a: 1 };
};

const cols = await figma.variables.getLocalVariableCollectionsAsync();
const prim = cols.find((c) => c.name === '01 Primitives');
const sem = cols.find((c) => c.name === '02 Semantic');
if (!prim || !sem) throw new Error('expected collections "01 Primitives" and "02 Semantic"');

const primMode = prim.modes[0].modeId;
const light = sem.modes.find((m) => m.name === 'Light');
const dark = sem.modes.find((m) => m.name === 'Dark');
if (!light || !dark) throw new Error('expected Light and Dark modes on "02 Semantic"');

const primVars = await Promise.all(prim.variableIds.map((id) => figma.variables.getVariableByIdAsync(id)));
const semVars = await Promise.all(sem.variableIds.map((id) => figma.variables.getVariableByIdAsync(id)));
const byPrim = {}; primVars.forEach((v) => { byPrim[v.name] = v; });
const bySem = {}; semVars.forEach((v) => { bySem[v.name] = v; });

let created = 0, updated = 0;
for (const [name, hex] of pairs(PRIM)) {
  let v = byPrim[name];
  if (!v) { v = figma.variables.createVariable(name, prim, 'COLOR'); byPrim[name] = v; created++; }
  else updated++;
  v.setValueForMode(primMode, hexToRgb(hex));
}

/* Collected rather than thrown on, so a rename shows every casualty at once
   instead of one per run. A partial write is still visible in the counts. */
let repointed = 0; const missing = [];
for (const [mode, list] of [[light.modeId, LIGHT], [dark.modeId, DARK]]) {
  for (const [token, target] of pairs(list)) {
    const t = bySem[token]; const src = byPrim[target];
    if (!t) { missing.push('semantic ' + token); continue; }
    if (!src) { missing.push('primitive ' + target); continue; }
    t.setValueForMode(mode, figma.variables.createVariableAlias(src));
    repointed++;
  }
}

console.log('file      :', figma.root.name);
console.log('created   :', created, 'primitives');
console.log('updated   :', updated, 'primitives');
console.log('repointed :', repointed, 'semantic bindings across both modes');
if (missing.length) console.log('MISSING   :', missing.join(', '));
return { file: figma.root.name, created, updated, repointed, missing };
