/**
 * Emits src/styles/tokens.css from tokens/tokens.json.
 *
 *   node tokens/css.mjs        (or: npm run tokens)
 *
 * Three things come out:
 *
 *   :root                       every primitive, plus semantic.light
 *   @media (prefers-color-scheme: dark) / [data-theme="dark"]
 *                               semantic.dark
 *   [data-band]                 band roles, which re-declare the semantic
 *                               properties for their subtree
 *
 * That last part is the whole banding system in CSS. `inverse` is not a
 * separate palette — it re-declares the same properties with the other mode's
 * values, which is why a component dropped inside an inverse band flips with
 * no override. See docs/banding-system.md.
 *
 * Generated. Do not edit src/styles/tokens.css by hand.
 */
import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const here = dirname(fileURLToPath(import.meta.url));
const root = join(here, '..');
const t = JSON.parse(readFileSync(join(here, 'tokens.json'), 'utf8'));

const flatten = (node, path = [], out = []) => {
  for (const [k, v] of Object.entries(node)) {
    if (k.startsWith('$')) continue;
    if (v && v.$value !== undefined) out.push([[...path, k].join('-'), v]);
    else if (v && typeof v === 'object') flatten(v, [...path, k], out);
  }
  return out;
};

const dig = (o, p) => p.split('.').reduce((a, k) => (a == null ? a : a[k]), t);

/** Alias {a.b.c} -> var(--a-b-c); everything else passes through. */
function value(v) {
  if (typeof v !== 'string') return v;
  const m = /^\{(.+)\}$/.exec(v);
  return m ? `var(--${m[1].replace(/\./g, '-')})` : v;
}
const isAlias = (v) => typeof v === 'string' && /^\{.+\}$/.test(v);

function render(entry) {
  const [name, node] = entry;
  const v = node.$value;
  if (node.$type === 'typography') return null;          // text styles become classes, below
  if (isAlias(v)) return [`--${name}`, value(v)];        // semantic tokens alias primitives
  if (node.$type === 'cubicBezier') return [`--${name}`, `cubic-bezier(${v.join(', ')})`];
  if (node.$type === 'shadow') {
    const layers = (Array.isArray(v) ? v : [v])
      .map((s) => `${s.offsetX} ${s.offsetY} ${s.blur} ${s.spread} ${s.color}`).join(', ');
    return [`--${name}`, layers];
  }
  if (node.$type === 'gradient') {
    const stops = v.map((s) => `${s.color} ${Math.round(s.position * 100)}%`).join(', ');
    return [`--${name}`, `linear-gradient(135deg, ${stops})`];
  }
  return [`--${name}`, value(v)];
}

const lines = [];
lines.push('/* Generated by tokens/css.mjs — do not edit. Run: npm run tokens */', '');

// ---- primitives + light semantics ----------------------------------------
lines.push(':root {');
for (const e of flatten(t.primitive, ['primitive'])) { const r = render(e); if (r) lines.push(`  ${r[0]}: ${r[1]};`); }
lines.push('');
for (const e of flatten(t.semantic.light, ['semantic'])) { const r = render(e); if (r) lines.push(`  ${r[0]}: ${r[1]};`); }
lines.push('');
for (const e of flatten(t.shadow, ['shadow'])) { const r = render(e); if (r) lines.push(`  ${r[0]}: ${r[1]};`); }
for (const e of flatten(t.gradient, ['gradient'])) { const r = render(e); if (r) lines.push(`  ${r[0]}: ${r[1]};`); }
lines.push('}', '');

// ---- dark semantics -------------------------------------------------------
const darkDecls = flatten(t.semantic.dark, ['semantic']).map(render).filter(Boolean)
  .map(([k, v]) => `    ${k}: ${v};`).join('\n');
lines.push('@media (prefers-color-scheme: dark) {', '  :root:not([data-theme="light"]) {', darkDecls, '  }', '}', '');
lines.push('[data-theme="dark"] {', darkDecls.replace(/^ {4}/gm, '  '), '}', '');

// ---- bands ---------------------------------------------------------------
// A band re-declares the semantic properties for its subtree. `inverse` is the
// same band under the other mode — not a separate palette.
const lightDecls = flatten(t.semantic.light, ['semantic']).map(render).filter(Boolean);
const darkPairs = Object.fromEntries(flatten(t.semantic.dark, ['semantic']).map(render).filter(Boolean));
const asBlock = (pairs, indent) => pairs.map(([k, v]) => `${indent}${k}: ${v};`).join('\n');

lines.push('/* Bands. A band owns the foreground of everything inside it. */');
lines.push('[data-band] { background: var(--semantic-band-base); color: var(--semantic-fg-primary); }');
lines.push('[data-band="sunken"] { background: var(--semantic-band-sunken); }', '');
lines.push('/* inverse = the same band in the other theme, so every semantic property flips */');
lines.push('[data-band="inverse"], [data-band="inverse-raised"] {');
lines.push(asBlock(Object.entries(darkPairs), '  '));
lines.push('  background: var(--semantic-band-base);');
lines.push('}');
lines.push('[data-band="inverse-raised"] { background: var(--semantic-band-sunken); }', '');
lines.push('@media (prefers-color-scheme: dark) {');
lines.push('  :root:not([data-theme="light"]) [data-band="inverse"],');
lines.push('  :root:not([data-theme="light"]) [data-band="inverse-raised"] {');
lines.push(asBlock(lightDecls, '    '));
lines.push('  }');
lines.push('}');
lines.push('[data-theme="dark"] [data-band="inverse"],');
lines.push('[data-theme="dark"] [data-band="inverse-raised"] {');
lines.push(asBlock(lightDecls, '  '));
lines.push('}', '');

// ---- over media ----------------------------------------------------------
// Bands are relative: `inverse` means "this band, in the other theme", so it
// flips when the theme flips. That is right for a band whose fill is a token.
//
// It is wrong over a photograph. A photograph is dark in both themes, so a
// relative role sends the foreground the wrong way in one of them: white text
// in light mode, dark text in dark mode, over the same dark image. bg/scrim
// weakens from 70% to 40% at the same moment, so the contrast drops exactly
// where it was already doing the most work.
//
// This is absolute. It always resolves to the dark-mode values, whatever the
// page theme is, because the surface underneath it does not change. Emitted
// last so it wins over the theme blocks above.
lines.push('/* Content over media. Absolute, not relative: the image is dark in both themes. */');
lines.push('[data-on-media] {');
lines.push(asBlock(Object.entries(darkPairs), '  '));
lines.push('}', '');

// ---- type styles ----------------------------------------------------------
// Emitted twice, from the same source, for two different consumers.
//
// Custom properties are what component CSS uses. A class cannot be composed
// inside a rule, and responsive type here means stepping between two styles on
// the scale at a breakpoint rather than clamping to an off-scale value, which
// needs the longhands available as properties.
//
// The classes stay for markup that takes a whole style as-is.
const typeStyles = flatten(t.typography, []);
const family = (f) => (f === 'Inter' ? 'Inter, system-ui, sans-serif' : `'${f}', Inter, system-ui, sans-serif`);

lines.push('/* Text styles as properties. Component CSS binds to these, never to raw values. */');
lines.push(':root {');
for (const [name, node] of typeStyles) {
  const v = node.$value;
  lines.push(`  --type-${name}-family: ${family(v.fontFamily)};`);
  lines.push(`  --type-${name}-weight: ${v.fontWeight};`);
  lines.push(`  --type-${name}-size: ${v.fontSize};`);
  lines.push(`  --type-${name}-line: ${v.lineHeight};`);
  lines.push(`  --type-${name}-tracking: ${v.letterSpacing};`);
  // Shorthand for the common case. letter-spacing is not part of `font`, so it
  // is always applied separately.
  lines.push(`  --type-${name}: ${v.fontWeight} ${v.fontSize}/${v.lineHeight} ${family(v.fontFamily)};`);
}
lines.push('}', '');

lines.push('/* The same styles as classes, for markup that takes one whole. */');
for (const [name] of typeStyles) {
  lines.push(`.type-${name} { font: var(--type-${name}); letter-spacing: var(--type-${name}-tracking); }`);
}

mkdirSync(join(root, 'src', 'styles'), { recursive: true });
writeFileSync(join(root, 'src', 'styles', 'tokens.css'), lines.join('\n') + '\n');

const count = (o) => flatten(o, []).length;
console.log('src/styles/tokens.css written');
console.table({
  primitives: count(t.primitive),
  'semantic (per mode)': count(t.semantic.light),
  typography: count(t.typography),
  shadow: count(t.shadow),
  gradient: count(t.gradient)
});
